### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Bokt\Phpbb\Models\AclGroup::getGroup()

### ISSUE THREAD

**Issue by gustjoha** [Bokt/flarum-phpbb-migrate#3]
Migration for forum:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Bokt\Phpbb\Models\AclGroup::getGroup() must be an instance of Bokt\Phpbb\Models\Group, null given, called in /path/to/flarum/vendor/bokt/flarum-phpbb-migrate/src/Models/AclGroup.php on line 47 and defined in /path/to/flarum/vendor/bokt/flarum-phpbb-migrate/src/Concerns/ReplacesGenericGroups.php:17
Stack trace:
#0 /path/to/flarum/vendor/bokt/flarum-phpbb-migrate/src/Models/AclGroup.php(47): Bokt\Phpbb\Models\AclGroup->getGroup(NULL)
#1 /path/to/flarum/vendor/bokt/flarum-phpbb-migrate/src/Models/Forum.php(93): Bokt\Phpbb\Models\AclGroup->import()
#2 /path/to/flarum/vendor/illuminate/database/Concerns/BuildsQueries.php(62): Bokt\Phpbb\Models\Forum->Bokt\Phpbb\Models\{closure}(Object(Bokt\Phpbb\Models\AclGroup), 2)
#3 /path/to/flarum/vendor/illuminate/database/Concerns/BuildsQueries.php(39): Illuminate\Database\Eloquent\Builder->Illuminate\Database\ in /home/hockeyb/beta.hockeybulletin.se/vendor/bokt/flarum-phpbb-migrate/src/Concerns/ReplacesGenericGroups.php on line 17
```

**Comment by jslirola** [comment]
I get the same error. This is the output of `var_dump($this)`:

`{"group_id":3,"forum_id":1,"auth_option_id":0,"auth_role_id":15,"auth_setting":0,"group":null}"`

I'll try to figure it out what's the cause.
